preprocess:
    remove_stop_words: False
    train_random_seed: 1
    test_random_seed: 2
    val_split_ratio: 0.1
    min_word_freq: 1
    dataset: 'mr'
    train_data_dir: './data/mr/train'
    test_data_dir: './data/mr/test'
    graph_root_dir: './data/'
    data_root_dir: './data/'
    embed_dim: 300
    window_size_for_PMI: 20 
    min_PMI: 0
    word_word_edge_weight: 'PMI'
    doc_word_edge_weight: 'TF-IDF'
