preprocess:
    remove_stop_words: True
    train_random_seed: 1
    test_random_seed: 2
    val_split_ratio: 0.1
    min_word_freq: 5
    train_data_dir: '../data/20NG/20news-bydate-train'
    test_data_dir: '../data/20NG/20news-bydate-test'

