preprocess:
    remove_stop_words: True
    train_random_seed: 1
    test_random_seed: 2
    val_split_ratio: 0.1
    min_word_freq: 5
    dataset: '20ng'
    train_data_dir: '../data/20ng/20news-bydate-train'
    test_data_dir: '../data/20ng/20news-bydate-test'
    graph_root_dir: '../data/'
    data_root_dir: '../data/'
    window_size_for_PMI: 20 
    min_PMI: 0
    embed_dim: 300
    word_word_edge_weight: 'PMI'
    doc_word_edge_weight: 'TF-IDF'
training:
    model: 'transformer'
    embed_dim: 300
    nhead: 5
    nhid: 200
    nlayers: 2
    batch_size: 4
    lr: 0.0001
    grad_clip: 10
    print_iter: 100000
    dropout: 0.2
    weight_decay: 0
    epochs: 50
    max_doc_len: 100
    model_dir: "saved_models"
    id: 1
    lr_decay_ratio: 0.95